MyWebsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls_staff')),
]

app/models.py
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify

# Create your models here.
class Category(models.Model):
    #code = models.CharField(max_length=20, verbose_name='Mã danh mục', unique=True, null=True, blank=True)
    name = models.CharField(max_length=200, verbose_name='Tên danh mục', unique=True)
    slug = models.CharField(max_length=200, verbose_name='Slug danh mục', unique=True, null=True, blank=True)
    status = models.BooleanField(verbose_name='Trang thái')
    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Danh mục')
    code = models.CharField(max_length=10, verbose_name='Mã', unique=True)
    name = models.CharField(max_length=200, verbose_name='Tên', unique=True)
    slug = models.CharField(max_length=200, verbose_name='Tên SEO',null=True, blank=True)
    #image = models.ImageField(upload_to='static/images', verbose_name='Ảnh', null=True, blank=True)
    #image_list = models.CharField(max_length=500, verbose_name='Ảnh chi tiết', null=True, blank=True)
    price = models.FloatField(verbose_name='giá')
    discount = models.FloatField(default=None, verbose_name='giảm giá', null=True, blank=True)
    content = models.TextField(max_length=500, verbose_name='mô tả', null=True, blank=True)
    status = models.BooleanField(verbose_name='trạng thái')

    def __str__(self):
        return self.name

def get_image_filename(instance, filename):
    name = instance.Product.name
    slug = slugify(name)
    return "static/images/%s-%s" % (slug, filename)
    
class ImagesProduct(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    #main_image = models.ImageField(upload_to='static/images/', verbose_name='ảnh chính', null=True, blank=True)
    image = models.ImageField(upload_to='static/images/', verbose_name='ảnh chi tiết')

class Customer(models.Model):
    code = models.CharField(max_length=10, verbose_name='Mã', unique=True)
    name = models.CharField(max_length=200, verbose_name='Tên')
    email = models.CharField(max_length=200, verbose_name='Email', unique=True)
    password = models.CharField(max_length=200, verbose_name='Mật khẩu')
    remember_token = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    code = models.CharField(max_length=10, verbose_name='Mã', unique=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, verbose_name='Mã khách hàng')
    phone = models.IntegerField(verbose_name='Số điện thoại')
    address = models.TextField(verbose_name='Địa chỉ giao hàng')
    order_note = models.TextField(verbose_name='Ghi chú đơn hàng') 
    created_order = models.DateTimeField(verbose_name='Ngày tạo đơn hàng')
    status = models.IntegerField(verbose_name='trạng thái')

    class OrderStatus:
        XacNhan = 0
        DangGiao = 1
        DaGiao = 2
        GiaoThatBai = 3
        HuyDonHang = 4

    def __str__(self):
        return self.code

class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name="mã đơn hàng")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="sản phẩm")
    quantity = models.IntegerField(verbose_name="số lượng")
    price = models.FloatField(verbose_name="Giá")

class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="mã sản phẩm")
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name="mã khách hàng")
    content = models.TextField(verbose_name='nội dung')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')

    def __str__(self):
        return self.content

class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, verbose_name="mã bình luận")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="mã người trả lời")
    content = models.TextField(verbose_name="nội dung")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')

    def __str__(self):
        return self.content

class Event(models.Model):
    code = models.CharField(max_length=10, verbose_name='Mã sự kiện', unique=True)
    name = models.TextField(verbose_name='Tên sự kiện')
    description = models.TextField(verbose_name='mô tả sự kiện', null=True, blank=True)
    start_date = models.DateTimeField(verbose_name='ngày bắt đầu')
    end_date = models.DateTimeField(verbose_name='ngày kết thúc')

    def __str__(self):
        return self.name

class Sale(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name='mã sự kiện')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='mã sản phẩm')
    discount = models.FloatField(verbose_name="khuyến mại")
    same_price = models.FloatField(verbose_name="đồng giá", null=True, blank=True)

    
    

app/forms.py
from django import forms
from .models import *

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name','slug', 'status')

class ProductForm(forms.ModelForm):
    #image = forms.ImageField(widget=forms.FileInput(attrs={'multiple': ''}))
    #name = forms.CharField(max_length=128)
    
    class Meta:
        model = Product
        fields = '__all__'

class ImagesProductForm(forms.ModelForm):
    image = forms.ImageField(label='ảnh chi tiết')
    #main_image = forms.ImageField(label='ảnh chính')
    class Meta:
        model = ImagesProduct
        fields = ('image',)

class SomeForm(forms.Form):
    text = forms.CharField(widget = forms.Textarea(attr={'class':'richtexteditor'})

app/views.py
from django.shortcuts import render

# Create your views here.

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Blank Page</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'admin/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'admin/dist/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <style>
        ul.errorlist{
            color: red;
            list-style-type: none;
        }
    </style>
    <script type="text/javascript">
        var base_url = function(){
            
        }
        var akey = function(){
            
        }
    </script>
</head>
<h1>{{current_path}}</h1>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Contact</a>
                </li>
            </ul>

            <!-- SEARCH FORM -->
            <form class="form-inline ml-3">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
                    </div>
                </div>
            </form>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Messages Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-comments"></i>
                        <span class="badge badge-danger navbar-badge">3</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="{% static 'admin/dist/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        Brad Diesel
                                        <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">Call me whenever you can...</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="{% static 'admin/dist/img/user8-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        John Pierce
                                        <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">I got your message bro</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="{% static 'admin/dist/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        Nora Silvester
                                        <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">The subject goes here</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                    </div>
                </li>
                <!-- Notifications Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-bell"></i>
                        <span class="badge badge-warning navbar-badge">15</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-item dropdown-header">15 Notifications</span>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-envelope mr-2"></i> 4 new messages
                            <span class="float-right text-muted text-sm">3 mins</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-users mr-2"></i> 8 friend requests
                            <span class="float-right text-muted text-sm">12 hours</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-file mr-2"></i> 3 new reports
                            <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                        <i class="fas fa-th-large"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="#" class="brand-link">
                <img src="{% static 'admin/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">AdminLTE 3</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="{% static 'admin/dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Alexander Pierce</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Dashboard
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Dashboard v1</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Dashboard v2</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Dashboard v3</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>Blank Page</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">Blank Page</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            {%block content %} {%endblock%}
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.0.5
            </div>
            <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->


    <!-- jQuery -->
    <script src="{% static 'admin/plugins/jquery/jquery.min.js' %}"></script>
    <!-- <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> -->
    <!-- Bootstrap 4 -->
    <script src="{% static 'admin/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'admin/dist/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'admin/dist/js/demo.js' %}"></script>
    <script src="{% static 'admin/dist/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'admin/dist/tinymce/config.js' %}"></script>
    <script src="{% static 'admin/ckeditor/ckeditor.js' %}"></script>
    {%block js%} 
    {%endblock%}

</body>

</html>

app/templates/category/add.html
 {% extends '../base.html' %} {%block content %}

<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Title</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i>
        </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i>
        </button>
            </div>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {%csrf_token%}

                <div class="form-group">
                    <label for="exampleInputPassword1">Tên danh mục</label> {{ form.name }} {{form.name.errors}}
                </div>
                <div class="form-group">
                    <label>slug danh mục</label> {{ form.slug }} {{form.slug.errors}}
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Hiện thị :</label> {{ form.status }}
                </div>


                <button class="btn btn-primary" type="submit">Lưu lại</button>
            </form>
        </div>
        <!-- /.card-body -->
        <div class="card-footer"></div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>



{%endblock%} {%block js%}

<script type="text/javascript">
    $(document).ready(() => {
        $("form input").addClass("form-control");
    });

    $('input#id_name').keyup(function(event) {
        var title, slug;
        //Lấy text từ thẻ input title 
        title = $(this).val();
        //Đổi chữ hoa thành chữ thường
        slug = title.toLowerCase();
        //Đổi ký tự có dấu thành không dấu
        slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
        slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
        slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
        slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
        slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
        slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
        slug = slug.replace(/đ/gi, 'd');
        //Xóa các ký tự đặt biệt
        slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
        //Đổi khoảng trắng thành ký tự gạch ngang
        slug = slug.replace(/ /gi, "-");
        //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
        //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
        slug = slug.replace(/\-\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-/gi, '-');
        slug = slug.replace(/\-\-/gi, '-');
        //Xóa các ký tự gạch ngang ở đầu và cuối
        slug = '@' + slug + '@';
        slug = slug.replace(/\@\-|\-\@|\@/gi, '');
        //In slug ra textbox có id “slug”
        $('input#id_slug').val(slug);
    });
</script>
{%endblock%}

app/templates/category/edit.html
{% extends '../base.html' %} {%block content %}

<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Sửa danh mục</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i>
        </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i>
        </button>
            </div>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {%csrf_token%}

                <div class="form-group">
                    <label for="exampleInputPassword1">Tên danh mục</label> {{ form.name }} {{form.name.errors}}
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Hiện thị :</label> {{ form.status }}
                </div>


                <button class="btn btn-primary" type="submit">Lưu lại</button>
            </form>
        </div>
        <!-- /.card-body -->
        <div class="card-footer"></div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>



{%endblock%} {%block js%}
<script type="text/javascript">
    $(document).ready(() => {
        $("form input").addClass("form-control");
    });
</script>
{%endblock%}

app/templates/index.html
{% extends 'base.html' %}




{%block content %}
      <h2>Trang chu admin</h2>
{%endblock%}

app/templates/product/add.html
{% extends '../base.html' %} {%block content %}


<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thêm sản phẩm</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fas fa-minus"></i>
        </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fas fa-times"></i>
        </button>
            </div>
        </div>
        <div class="card-body">
            <form id="aa_form" method="post" action="" enctype="multipart/form-data">

                {% csrf_token %}
                {% for hidden in productForm.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
            
                <!-- {% for field in productForm %}
                    {{ field.code }} <br />
                    {{ field.name }} <br />
                    {{ field.slug }} <br />
                {% endfor %} -->
                <div class="form-group">
                    <label for="">Mã sản phẩm</label> {{ productForm.code }} {{productForm.code.errors}}
                </div>
                <div class="form-group">
                    <label for="">Tên sản phẩm</label> {{ productForm.name }} {{productForm.name.errors}}
                </div>
                <div class="form-group">
                    <label for="">Tên SEO sản phẩm</label> {{ productForm.slug }} {{productForm.slug.errors}}
                </div>
                <div class="form-group">
                    <label for="">Danh mục sản phẩm</label> {{ productForm.category }} {{productForm.category.errors}}
                </div>
                <div class="form-group">
                    <label for="">Giá sản phẩm</label> {{ productForm.price }} {{productForm.price.errors}}
                </div>
               
                <div class="form-group">
                    <label for="">Mô tả sản phẩm</label> {{ productForm.content }} {{form.content.errors}}
                </div>
                <div class="form-group">
                    <label for="">Hiện thị :</label> {{ productForm.status }}
                </div>
                

            
                {{ formset.management_form }}
                {% for form in formset %}
                    {{ form }}
                {% endfor %}
            
            
                <input type="submit" name="submit" value="Lưu" class="btn btn-primary" />
            </form>

            <!-- <form action="" method="post" enctype="multipart/form-data">
                {%csrf_token%}

                <div class="form-group">
                    <label for="">Mã sản phẩm</label> {{ form.code }} {{form.code.errors}}
                </div>
                <div class="form-group">
                    <label for="">Tên sản phẩm</label> {{ form.name }} {{form.name.errors}}
                </div>
                <div class="form-group">
                    <label for="">Danh mục sản phẩm</label> {{ form.category }} {{form.category.errors}}
                </div>
                <div class="form-group">
                    <label for="">Giá sản phẩm</label> {{ form.price }} {{form.price.errors}}
                </div>
                <div class="form-group">
                    <label for="">Ảnh sản phẩm</label> {{ form.image }} {{form.image.errors}}
                </div>
                <div class="form-group">
                    <label for="">Mô tả sản phẩm</label> {{ form.content }} {{form.content.errors}}
                </div>
                <div class="form-group">
                    <label for="">Hiện thị :</label> {{ form.status }}
                </div>



                <button class="btn btn-primary" type="submit">Lưu lại</button>
            </form> -->
        </div>
        <div class="card-footer"></div>
    </div>
</section>



{%endblock%} 
{%block js%}
<script type="text/javascript">
    $(document).ready(() => {
        $("form input").addClass("form-control");
        $("form select").addClass("form-control");
        $("form textarea").addClass("form-control");
    });

    $('input#id_name').keyup(function(event) {
        var title, slug;
        //Lấy text từ thẻ input title 
        title = $(this).val();
        //Đổi chữ hoa thành chữ thường
        slug = title.toLowerCase();
        //Đổi ký tự có dấu thành không dấu
        slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
        slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
        slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
        slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
        slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
        slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
        slug = slug.replace(/đ/gi, 'd');
        //Xóa các ký tự đặt biệt
        slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
        //Đổi khoảng trắng thành ký tự gạch ngang
        slug = slug.replace(/ /gi, "-");
        //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
        //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
        slug = slug.replace(/\-\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-/gi, '-');
        slug = slug.replace(/\-\-/gi, '-');
        //Xóa các ký tự gạch ngang ở đầu và cuối
        slug = '@' + slug + '@';
        slug = slug.replace(/\@\-|\-\@|\@/gi, '');
        //In slug ra textbox có id “slug”
        $('input#id_slug').val(slug);
    });
</script>
{%endblock%}

app/templates/product/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form id="aa_form" method="post" action="" enctype="multipart/form-data">

    {% csrf_token %}
    {% for hidden in productForm.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in productForm %}
        {{ field }} <br />
    {% endfor %}

    {{ formset.management_form }}
    {% for form in formset %}
        {{ form }}
    {% endfor %}


    <input type="submit" name="submit" value="Submit" />
</form>
</body>
</html>